#!/bin/bash

# 1. Extract raw data using jq
name=$(jq -r '.name' data.json)
height=$(jq -r '.height' data.json)
weight=$(jq -r '.weight' data.json)
type=$(jq -r '.types[0].type.name' data.json)

# 2. Process the data using awk and sed
formatted_height=$(echo "$height" | awk '{printf "%.1f", $1/10}')
formatted_weight=$(echo "$weight" | awk '{printf "%d", $1/10}')
name=$(echo "$name" | sed 's/./\u&/')
type=$(echo "$type" | sed 's/./\u&/')

# 3. Assemble the final output
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."